name: Release

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  release:
    needs:
      - checks
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}